#theme: jekyll-theme-slate

title: Workshop Management of Scientific Data

description: Capturing and Documenting Provenance of Workflows with Kepler

author: Project-Team 03_02

navbar-links:
  Home: welcome.md
  About Me: about.md

navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-border-col: "#EAEAEA"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
